### ISSUE TITLE
swicw produces different results than smartweave

### ISSUE THREAD

**Issue by alexander-morris** [koii-network/kohaku#1]
![image](https://user-images.githubusercontent.com/37120777/128661583-f71121bb-cf5f-4a88-b28d-6ebeaddabc22.png)

I think this is related to the registration timing issues we discussed before, added a branch with output logging which displays these two files. Left is scicw (2.json) and right (1.json) is the standard Smartweave output. It seems that everything is the same except the ids in the data array at the end.

**Comment by AndreVallestero** [comment]
Resolved by https://github.com/koii-network/kohaku/commit/4e06f2af5aff798970017d814eba52380191bf70
